CREATE TABLE TBG_DETALHES_PROJETO (
    id BIGSERIAL PRIMARY KEY,
    projeto_id BIGINT NOT NULL,
    descricao TEXT NOT NULL,
    CONSTRAINT fk_projeto FOREIGN KEY (projeto_id) REFERENCES TBG_PROJETO(id) ON DELETE CASCADE
);
