CREATE TABLE TBG_USUARIO_TAREFA (
    id BIGSERIAL PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tarefa_id BIGINT NOT NULL,
    data_vinculo DATE NOT NULL,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES TBG_USER(id) ON DELETE CASCADE,
    CONSTRAINT fk_tarefa FOREIGN KEY (tarefa_id) REFERENCES TBG_TAREFA(id) ON DELETE CASCADE
);
