ALTER TABLE TBG_TAREFA
ADD COLUMN tarefa_id BIGINT,
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PLANEJADO';

ALTER TABLE TBG_TAREFA
ADD CONSTRAINT fk_tarefa_pai FOREIGN KEY (tarefa_id) REFERENCES TBG_TAREFA(id) ON DELETE CASCADE;
